name: Coleta diária
on:
  schedule:
    # meia-noite todos os dias
    - cron: '0 0 * * *'
jobs:
  scrap:
    name: Raspador do Vacinometro
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Instala as dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Raspa dados do vacinômetro
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
      run: scrapy crawl vaccines
