name: Coleta diária
on:
  schedule:
    # At the end of every day
    - cron: '*/10 * * * *'
jobs:
  scrap:
    name: Raspador do Vacinometro
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Instala as dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Raspa dados do vacinômetro
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
      run: GOOGLE_SHEET_ID=$GOOGLE_SHEET_ID GOOGLE_CREDENTIALS=$GOOGLE_CREDENTIALS scrapy crawl vaccines
