name: Daily Scrapper
on:
  schedule:
    # At the end of every day
    - cron: '*/10 * * * *'
jobs:
  scrap:
    name: Vacinometro Scrapper
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Scrap Vacinometro Website
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
      run: scrapy crawl vaccines
