name: Daily Scrapper
on:
  schedule:
    # At the end of every day
    - cron: '0 0 * * *'
jobs:
  scrap:
    name: Vacinometro Scrapper
    runs-on: ubuntu-latest
    steps:
    - name: Scrap Vacinometro Website
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
      run: poetry run scrapy crawl vaccines
